<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'" Label="Microsoft.Extensions">
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.*" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="8.*" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'" Label="Microsoft.Extensions">
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.*" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.*" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'" Label="Microsoft.Extensions">
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.*" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="10.*" />
  </ItemGroup>
  <ItemGroup Label="Application Packages">
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="NodaTime" Version="3.2.2" />
    <PackageVersion Include="CaseConverter" Version="2.0.1" />
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.21.0" />
    <PackageVersion Include="Ardalis.GuardClauses" Version="5.0.0" />
    <PackageVersion Include="SharpZipLib" Version="1.4.2" />
    <PackageVersion Include="Apache.NMS.ActiveMQ" Version="2.2.0" />
    <PackageVersion Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.2.5" />
  </ItemGroup>
  <ItemGroup Label="Testing Packages">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="NSubstitute" Version="6.0.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="NetArchTest.Rules" Version="1.3.2" />
  </ItemGroup>
</Project>
