<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <Configurations>Debug;Release</Configurations>
        <LangVersion>latestmajor</LangVersion>
        <Platforms>AnyCPU;x86;x64;ARM64</Platforms>
        <Version>1.0.106.0</Version>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <DebugSymbols>False</DebugSymbols>
        <DebugType>None</DebugType>
        <DefineConstants />
    </PropertyGroup>

    <PropertyGroup Label="nuget">
        <IsPackable>true</IsPackable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>RapidStreamer</Authors>
        <Description>Redefining real time data streaming; effortless, blazingly fast and cloud-native for maximum impact</Description>
        <Copyright>Copyright ©2024 RapidStreamer Corporation</Copyright>
        <PackageProjectUrl>https://www.rapidstreamer.com</PackageProjectUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/KAB-TEAM/RapidStreamer.BuildingBlocks</RepositoryUrl>
        <PackageTags>Real-Time Data Streaming, Blazingly Fast, Cloud-Native, Data Streaming, Effortless Performance, High Impact, Real-Time Processing, Fast Data Pipelines, Cloud Solutions, Streaming Technology</PackageTags>
        <PackageIcon>RapidStreamer.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <AvoidCycleErrorOnSelfReference>true</AvoidCycleErrorOnSelfReference>
        <PackageId Condition="'$(Configuration)' == 'Debug' And '$(Platform)' != 'AnyCPU'">RapidStreamer.BuildingBlocks.Debug.$(Platform)</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Debug' And '$(Platform)' == 'AnyCPU'">RapidStreamer.BuildingBlocks.Debug</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Release' And '$(Platform)' != 'AnyCPU'">RapidStreamer.BuildingBlocks.$(Platform)</PackageId>
        <PackageId Condition="'$(Configuration)' == 'Release' And '$(Platform)' == 'AnyCPU'">RapidStreamer.BuildingBlocks</PackageId>
    </PropertyGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CaseConverter" Version="2.0.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="MessagePack" Version="3.1.3" />
        <PackageReference Include="MessagePackAnalyzer" Version="3.1.3">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NetJSON" Version="1.4.4" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="protobuf-net" Version="3.2.46" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.6.1" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
        <PackageReference Include="Ardalis.GuardClauses" Version="5.0.0" />
        <PackageReference Include="SharpZipLib" Version="1.4.2" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\RapidStreamer.png" Pack="true" Link="RapidStreamer.png" PackagePath="" />
        <None Include="..\..\README.md" Pack="true" Link="README.md" PackagePath="" />
    </ItemGroup>

</Project>
