name: Pack and Push

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

env:
  NuGetDirectory: ${{ github.workspace}}/nuget
  Version: "*.*.^.*"

jobs:
  project-version:
    runs-on: ubuntu-latest
    name: Update version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set project versions
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.6
        with:
          file: |
            "./BuildingBlocks/**/*.csproj", "./BuildingBlocks/**/*.nuspec", "./BuildingBlocks/**/AssemblyInfo.cs"
          version: ${{ env.Version }}
          
      - run: |
          git config user.name "Kiarash Minoo"
          git config user.email "yanis_1984@msn.com"
          git add .
          git commit -m "Update project version to ${{ steps.project-version.outputs.newVersion }}"
          git push
          
  pack_nugets:
    runs-on: ubuntu-latest
    name: Create nuget
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'          

      - run: | 
          pwd
          ls
          sudo sh ./pack.sh              
          git config user.name "Kiarash Minoo"
          git config user.email "yanis_1984@msn.com"
          git add .
          git commit -m "Packing nuget package version ${{ steps.project-version.outputs.newVersion }}"
          git push

  push-nuget:    
    runs-on: ubuntu-latest
    name: Deploy to myget    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'   
          source-url: https://www.myget.org/F/rapidstreamer/api/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.MYGET_APIKEY}}

      - name: Publish NuGet package
        run: dotnet nuget push '**/RapidStreamer*.nupkg' --skip-duplicate -k ${{ secrets.MYGET_APIKEY }}

