name: Pack and Push

on:
  push:
    branches:
      - 'develop'

defaults:
  run:
    shell: pwsh

permissions:
  contents: write

env:  
  Project_Version: "*.*.^.*"

jobs:
  versioning_and_pack:
    runs-on: ubuntu-24.04
    name: Update version and Pack and Push nuget packages
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [ARM64, x64, x86, Any CPU]
    env:
      ArtifactsDirectory: ${{ github.workspace }}/artifacts_${{ matrix.configuration }}_${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 #fetch-depth is needed for GitVersion

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x    

      - name: Set project versions
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.6
        with:
          file: |
            "**/*.csproj", "**/*.nuspec", "**/AssemblyInfo.cs"
          version: ${{ env.Project_Version }}

      - name: Build solution and generate NuGet packages
        run: |
          dotnet clean

          dotnet build --nologo -c ${{ matrix.configuration }} /p:Platform=${{ matrix.platform }}
          dotnet pack  --nologo -c ${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} -o ${{ env.ArtifactsDirectory }}

      - name: scp packages
        run: |
          mkdir -p ~/.ssh
          ${{ secrets.REMOTE_PUB_KEY }} >> ~/.ssh/authorized_keys
          scp ${{ env.ArtifactsDirectory }}/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE }}:/root/artifacts/${{ steps.update.outputs.newVersion }}"    
