name: Update Versions

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version for the project"
        required: true 
        type: string  
        default: "*.*.*.^"

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update version
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set project versions
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.6
        with:
          file: |
            "BuildingBlocks/**/*.csproj", "BuildingBlocks/**/*.nuspec", "BuildingBlocks/**/AssemblyInfo.cs"
          version: ${{ github.event.inputs.version }}
          
      - run: |
          pwd       
          ls
